### ISSUE TITLE
Release geographic_info to Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-geographic-info/geographic_info#39]
@SteveMacenski Here's a ticket to release to ROS Noetic. I had a quick look for any Python 3 related stuff that needs to be done; I don't see any Python 3 syntax errors using `python3 -m flake8 --select=E999 .`. For all stuff these wiki pages should be helpful

* http://wiki.ros.org/UsingPython3
* http://wiki.ros.org/noetic/Migration

- [x] Bump CMake version to avoid CMP0048 warning (see ros/catkin#1052) 
- [x] Make `geodesy` use `setuptools` instead of `distutils.core` (see ros/catkin#1048)
- [x] Create a rosdep key for `python3-pyproj` to replace [python-pyproj](https://index.ros.org/d/python-pyproj/) used by `geodesy`. https://github.com/ros/rosdistro/pull/24114
   * Debian: https://packages.debian.org/buster/python3-pyproj
   * Ubuntu: https://packages.ubuntu.com/focal/python3-pyproj
   * Fedora: https://koji.fedoraproject.org/koji/rpminfo?rpmID=20764115
   * Gentoo: https://packages.gentoo.org/packages/dev-python/pyproj
- [x] Assuming ROS Melodic and Noetic will both be released from the `master` branch, use [conditional dependencies](http://wiki.ros.org/UsingPython3/SourceCodeChanges#Conditional_Dependencies) on `ROS_PYTHON_VERSION` for `python-pyproj`/`python3-pyproj` and `python-catkin-pkg-modules`/`python3-catkin-pkg-modules` in `geodesy`.

(*edit: continued from https://github.com/ros/rosdistro/issues/21513#issuecomment-599804296*)

**Comment by SteveMacenski** [comment]
See @sloretz #40

**Comment by sloretz** [comment]
Resolved by https://github.com/ros/rosdistro/pull/24168
