### ISSUE TITLE
[ROS2 Foxy] Cannot use conversion functions from `geodesy`

### ISSUE THREAD

**Issue by mnissov** [ros-geographic-info/geographic_info#49]
I am trying to convert some `NavSatFix` messages to WGS84 and UTM. I know in ROS1 the conversion tools we usable by
```cpp
#include "geodesy/utm.h"
#include "geodesy/wgs84.h"
```
but this doesn't seem to work in ROS2 with the package installed by
```bash
sudo apt install ros-foxy-geodesy
```

I can't seem to find any example anywhere online of utilizing this package in ROS2, which would almost lead me to believe it hasn't yet been ported if not for the availability of `ros-foxy-geodesy` in apt. Any ideas what I'm doing wrong?

**Comment by navil2000** [comment]
Did the "sudo apt install ros-foxy-geodesy" command work for you? I'm not sure why it didn't work for me, and I ended up switching to the humble version, where I was able to install it.

**Comment by SteveMacenski** [comment]
https://build.ros2.org/search/?q=geodesy&Jenkins-Crumb=503ee6fb07243e0e3a3002e651f391971e27b2810d2278eae13c6ad89175c56b

Humble and newer. Foxy is EOL.
